application: iolggr
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /log
  script: main.app

- url: /api/.*
  script: backend.api

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /(device)/(.*)
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_dir: static

libraries:
- name: webapp2
  version: "2.5.2"
